### ISSUE TITLE
Bug in firefox

### ISSUE THREAD

**Issue by Grinyaha** [patrickkunka/easydropdown#82]
Now when I clicking on the menu, window scrolling to top :) Theme is Flax.
top: -10px; helped :)

**Comment by patrickkunka** [comment]
Ah makes sense actually - and my demos don't test a long scrolling page. Just a css issue thankfully, will try to push a new release today.

**Comment by patrickkunka** [comment]
Ended up changing to:
```css
.edd-select {
    position: absolute;
    opacity: 0;
    width: 100%;
    left: -100%;
    top: 0;
}
```

This seems to solve the issue of keeping the element hidden and unclickable, but still focusable, and without jumping the window if scrolled.

Released in https://github.com/patrickkunka/easydropdown/releases/tag/v4.0.5
